"""crear tablas dispositivo y ficha_tecnica

Revision ID: 1f09748021ad
Revises: 
Create Date: 2026-07-04 19:30:16.593600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f09748021ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo',
    sa.Column('id_dispositivo', sa.UUID(), nullable=False),
    sa.Column('nombre_busqueda', sa.String(length=200), nullable=False),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('url_oficial', sa.Text(), nullable=True),
    sa.Column('fecha_ultima_consulta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_dispositivo')
    )
    op.create_table('ficha_tecnica',
    sa.Column('id_ficha', sa.UUID(), nullable=False),
    sa.Column('id_dispositivo', sa.UUID(), nullable=False),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('procesador', sa.String(length=200), nullable=True),
    sa.Column('camara_principal', sa.String(length=200), nullable=True),
    sa.Column('almacenamiento', sa.String(length=100), nullable=True),
    sa.Column('precio_oficial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('contenido_raw', sa.Text(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.CheckConstraint('precio_oficial > 0', name='ck_precio_positivo'),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id_dispositivo'], ),
    sa.PrimaryKeyConstraint('id_ficha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ficha_tecnica')
    op.drop_table('dispositivo')
    # ### end Alembic commands ###
